### PR TITLE
Moves project build to ASF infrastructure

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This moves off non-ASF things including repositories, deployment
processes, license headers etc. It creates the same changes done
in brave-karaf. Later, we'll need to setup Jenkins to look at this
and also do a test release.

See #15

### CODE REVIEW

**Comment by reta** [comment]
Great one, @adriancole !

**Review by reta — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
I looked and this isn't producing the DEPENDENCIES file

**Review by shakuzen — APPROVED** [review]

**Comment by abesto** [comment]
Cool stuff. Keep in mind, once merged, we'll still need to click on the Jenkins UI to create a multi-branch pipeline job to pick up the Jenkinsfile (copying from brave-karaf should give us almost exactly what we need). Once we're up to ~5 builds, it might make sense to set up some DRY (many ways of doing that, best choice will likely come down to ASF-Jenkins plugins and permissions)

**Comment by codefromthecrypt** [comment]
moving on despite the DEPENDENCIES issue as that also exists in karaf so we can fix them together at some point https://github.com/apache/incubator-zipkin-brave-cassandra/issues/18

**Comment by codefromthecrypt** [comment]
> Cool stuff. Keep in mind, once merged, we'll still need to click on the
> Jenkins UI to create a multi-branch pipeline job to pick up the Jenkinsfile
> (copying from brave-karaf should give us almost exactly what we need). Once
> we're up to ~5 builds, it might make sense to set up some DRY (many ways of
> doing that, best choice will likely come down to ASF-Jenkins plugins and
> permissions)
>

I create the job copying
https://builds.apache.org/job/incubator-zipkin-brave-karaf/configure
I only changed Description and Branch Sources/Repository

**Pull request merged**
