### PR TITLE
Makes manual deployment exactly the same as Travis

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Before, we had travis/publish.sh which took concerns such as checking
Travis tags. Travis currently has conditions libraries and well-defined
stages. This uses these features instead as it allows us a more simple
relationship between what are release steps vs what are travis-specific.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
ps still trying to figure out why this isn't triggering on my PR..

**Comment by codefromthecrypt** [comment]
Lesson learned:

In the docker-java project, I took advantage of the implicit "test" phase, using the top-level "script" by default. 

This doesn't work when adding conditions on the "test" phase. In this case, you have to override it entirely the same as if defining the job from scratch.

**Comment by codefromthecrypt** [comment]
I'm going to merge this, then make a fake pull request from my fork, to ensure the PR works on non-head branches.

**Comment by codefromthecrypt** [comment]
this works, except that the status of the "test" phase isn't reported back on the fork PR https://github.com/openzipkin/brave-cassandra/pull/35

https://travis-ci.org/github/openzipkin/brave-cassandra/builds/742193067

**Pull request merged**
